agentName: mmagent04
envName: dev
namespace: mmagent04-dev

images:
  apiServerImage:
    repository: 229560443702.dkr.ecr.us-west-2.amazonaws.com/mmagent04
    tag: 6aab320461c773f084d0c2ff32eb4499afacf430

apiServer:
  service:
    type: ClusterIP

studio:
  service:
    type: ClusterIP

postgres:
  external:
    enabled: false
    secretManager:
      enabled: false
      secretName: postgres-secret
      secretKey: connectionUrl

config:
  existingSecretName: langgraph-cloud-secrets